---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-svc-monitor
  namespace: monitoring
  labels:
    prometheus: main
spec:
  namespaceSelector:
    matchNames:
      - demo
  selector:
    matchLabels:
      app: demo-nginx
      # isio: monitor
  endpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
      interval: 15s
      honorLabels: true